name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Environment set-up
        run: |
          sudo apt-get update && \
          sudo apt-get install -y build-essential cmake ninja-build zlib1g-dev
      - name: Binary Ninja SDK
        run: |
          mkdir -p /opt/binaryninja && \
          echo | gcc -shared -Wl,-soname,libbinaryninjacore.so.1 -Wl,-rpath=$ORIGIN \
            -o /opt/binaryninja/libbinaryninjacore.so.1 -x c -
      - name: C/C++
        run: |
          mkdir -p build && \
          cd build && \
          cmake -DCMAKE_BUILD_TYPE=Release -G Ninja .. && \
          cmake --build .
      - uses: actions/upload-artifact@v1
        with:
          name: libaarch64_extension.so
          path: $GITHUB_WORKSPACE/build/libaarch64_extension.so